// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy9gjgEXajqAmS2SED8kWqCtsSmSGlBC4',
    appId: '1:1083082446261:web:1816c7b6f4716a61f235fc',
    messagingSenderId: '1083082446261',
    projectId: 'my-mentat-health-project',
    authDomain: 'my-mentat-health-project.firebaseapp.com',
    storageBucket: 'my-mentat-health-project.firebasestorage.app',
    measurementId: 'G-X6N8QPCE2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your-android-api-key-here',
    appId: 'your-android-app-id-here',
    messagingSenderId: '1083082446261',
    projectId: 'my-mentat-health-project',
    storageBucket: 'my-mentat-health-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key-here',
    appId: 'your-ios-app-id-here',
    messagingSenderId: '1083082446261',
    projectId: 'my-mentat-health-project',
    storageBucket: 'my-mentat-health-project.firebasestorage.app',
    iosBundleId: 'com.example.giraInshuti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-ios-api-key-here',
    appId: 'your-ios-app-id-here',
    messagingSenderId: '1083082446261',
    projectId: 'my-mentat-health-project',
    storageBucket: 'my-mentat-health-project.firebasestorage.app',
    iosBundleId: 'com.example.giraInshuti',
  );
}